name: Deploy Bucket

#condicao: quando ocorrer um push para o branch 'github_actions', excecuta o workflow
on: 
  push:
    branches:
      - github_actions


jobs:
  test:
    #vai rodar num docker
    runs-on:  ubuntu-latest
    steps:
      #copia o codigo do repositorio pro docker - condicao propria do actions
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2 # tbm funcao do actions
        with:
          python-version: '3.x'
      - name: Install test dependencies
        run: |
          pip install -r tests/requirements.txt
      - name: Run tests
        run: python -m pytest


  deploy:
    needs: test
    #vai rodar num docker
    runs-on:  ubuntu-latest
    steps:
      #copia o codigo do repositorio pro docker - condicao propria do actions
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2 # tbm funcao do actions
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        run: |
            python aula2/github_actions/deploy.py


